### PR TITLE
fix issue in append_compact_purge example

### LINKED ISSUE #239: append_compact_purge example never compacts
Found in #237 

In this code snippet:

https://github.com/tikv/raft-engine/blob/7a436eae40a6b62371123c96941e058b7fe52b63/examples/append_compact_purge.rs#L59-L74

state.last_index is not updated in sync with entry index. Entries will never be compacted.

### PR DESCRIPTION
**Pull request by LykxSassinator**
## Brief description

This commit is used to close #239.

Signed-off-by: Lucasliang <nkcs_lykx@hotmail.com>

## Codes update
```Rust
diff --git a/examples/append_compact_purge.rs b/examples/append_compact_purge.rs
index b9ebc1a..0565e44 100644
--- a/examples/append_compact_purge.rs
+++ b/examples/append_compact_purge.rs
@@ -51,11 +51,11 @@ fn main() {
     loop {
         for _ in 0..1024 {
             let region = rand_regions.next().unwrap();
-            let state = engine
+            let mut state = engine
                 .get_message::<RaftLocalState>(region, b"last_index")
                 .unwrap()
                 .unwrap_or_else(|| init_state.clone());
-
+            state.last_index += 1; // manually update the state
             let mut e = entry.clone();
             e.index = state.last_index + 1;
             batch.add_entries::<MessageExtTyped>(region, &[e]).unwrap();
```

## Prints for bugfix
With this patch, the logging of `append_compact_purge` will contain:
```shell
[EXAMPLE] compact 298 to 192
[EXAMPLE] compact 56 to 631
[EXAMPLE] compact 262 to 321
[EXAMPLE] compact 80 to 758
[EXAMPLE] compact 177 to 800
[EXAMPLE] compact 150 to 803
[EXAMPLE] compact 257 to 365
[EXAMPLE] compact 66 to 700
[EXAMPLE] compact 151 to 841
[EXAMPLE] compact 205 to 628
```
And the above prints are expected.

### CODE REVIEW

File: examples/append_compact_purge.rs [hunk 1]
```diff
@@ -51,11 +51,11 @@ fn main() {
...
             let region = rand_regions.next().unwrap();
-            let state = engine
+            let mut state = engine
                 .get_message::<RaftLocalState>(region, b"last_index")
                 .unwrap()
                 .unwrap_or_else(|| init_state.clone());
-
+            state.last_index += 1; // manually update the state
             let mut e = entry.clone();
             e.index = state.last_index + 1;
```
Comment (tabokie) [inline examples/append_compact_purge.rs:60]:
```suggestion
            e.index = state.last_index;
```

**Review by tabokie — APPROVED** [review]
