### PR TITLE
fix data loss caused by atomic group being partially purged

### LINKED ISSUE #315: Atomic group causes data loss
Using dump tool, we locate the missing entry is in file X. File X is the oldest rewrite log available. Use dump tool to analyze file X, it only contains `AtomicGroup::Middle` but no `AtomicGroup::Begin`.

What happened is, memtable is not aware of the atomic group that each entry/kv belongs to. After user deletes some of the entries inside an atomic group, memtable will permit the purge thread to delete the physical files that contain these entries. As a result, the `Begin` marker of this atomic group is deleted. Next restart this group will be broken and all entries including those not deleted by user will disappear.

### PR DESCRIPTION
**Pull request by tabokie**
Close #315

Record the start and end position of an atomic group in memtable.

### CODE REVIEW

File: src/memtable.rs [hunk 1]
```diff
@@ -155,6 +155,16 @@ pub struct MemTable<A: AllocatorTrait> {
...
 
+    /// (start_seq, end_seq).
+    /// If there's an active entry stored before end_seq, it possibly belongs to
+    /// an atomic group. In order to not lose this entry, We cannot delete any
+    /// other entries in that group.
+    /// Only applies to Rewrite queue. Each Raft Group has at most one atomic
+    /// group at a time, because we only use atomic group for rewrite-rewrite
+    /// operation, a group always contains all the Rewrite entries in a Raft
+    /// Group.
+    atomic_group: Option<(FileSeq, FileSeq)>,
```
Comment (overvenus) [inline src/memtable.rs:166]: Is it possible to have two groups?

Comment (tabokie) [reply src/memtable.rs:166]: The comment above says there can only be one group at a time.

**Review by overvenus — APPROVED** [review]

**Review by tonyxuqqi — APPROVED** [review]
